name: dio_lumberdash
description: A Lumberdash interceptor for Dio
version: 0.0.1
author: Peter Bryant <peter.bryant@netsells.co.uk>
homepage: https://github.com/netsells/dio_lumberdash

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  lumberdash: ^3.0.0
  dio: ^4.0.0
